### ISSUE TITLE
Fixed file path

### ISSUE THREAD

**Issue by kabakakao** [bmachuletz/amcv360RequestRecorder#1]
In this line, you use a fixed file path. So it wouldn't work in other environments:
https://github.com/bmachuletz/amcv360RequestRecorder/blob/0b47c437bf633cc4c7818fe1cd1fe675e1787280/amcv/FileServer.cs#L27

Use instead:
Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "Certs", "public.cer")

**Comment by bmachuletz** [comment]
Uups.. Thank you. I‘ll fix it next week.

**Comment by bmachuletz** [comment]
Fixed path in Code
