### ISSUE TITLE
Didn't get entries after activating proxy

### ISSUE THREAD

**Issue by kabakakao** [bmachuletz/amcv360RequestRecorder#2]
I have installed the certificate and activated the proxy. But it didnt't work for me. I can't see any entries, after pushing "cleaning" or "charging" or whatever.
I seems, that you are searching for a special client name? (from=mpc_ios)

https://github.com/bmachuletz/amcv360RequestRecorder/blob/0b47c437bf633cc4c7818fe1cd1fe675e1787280/amcv/TitaniumEngine.cs#L115

**Comment by bmachuletz** [comment]
It‘s the application name. I think I can solve this by useing a Regel.
Will fix it next week.

**Comment by bmachuletz** [comment]
fixed the "if" clauses to match iOS and Android bodies.
Please let me know if this works.

**Comment by bmachuletz** [comment]
the above code fixed this issue. you'll have to fully trust the certificate on that device.
