### ISSUE TITLE
java.security.cert.CertPachValidatorException

### ISSUE THREAD

**Issue by elv1zzz** [bmachuletz/amcv360RequestRecorder#3]
hi. is it works with 360Smart AIv 5.1.0.0?
always when i try to do anything in app i receive error message
"java.security.cert.CertPachValidatorException: Trust anchor for certification path not found"

**Comment by bmachuletz** [comment]
Hi, you have to fully Trust the certificate on your mobile device. What is your android version?

**Comment by elv1zzz** [comment]
yes. cert was installed on my android 9 (samsung s9). but i tried to do similar on ios 10 with same result.

**Comment by bmachuletz** [comment]
I use the latest version on iOS. I couldn’t reproduce this Issue by now.  From Android onwards there seems  to be a security feature to not trust self signed certificates. I‘ll give it a try on an android tablet tomorrow evening.

**Comment by bmachuletz** [comment]
I‘ve checken this issue. On iOS it‘s working very well (Version 5.10). On my Android 8 device I am running into the same  Are you able to try it on an older android Version (7)?

**Comment by bmachuletz** [comment]
I‘ve checken this issue. On iOS it‘s working very well (Version 5.10). On my Android 8 device I am running into the same  Are you able to test it on an older android Version?

**Comment by elv1zzz** [comment]
xiaomi 4a (android 7) same error

**Comment by bmachuletz** [comment]
Hmm. I couldn‘t test it on android right now. On my iOS 12.3.1 (iPhone 8) there is no problem.

**Comment by unknownuser26** [comment]
Hello, I had the same problem.
I created a VM with Android x86 and stored the certificate as trusted via root, then everything worked so well. Unfortunately, it is probably a security feature of Android that self-signed certificates only work in the browser.

**Comment by bmachuletz** [comment]
Hi, very nice workaround. Can please Write down a small howto. So I can integrate ist on the GitHub page.
GreetzBenjamin
    	
    	

    	
    
  




On Fri, Sep 20, 2019 at 4:51 PM +0200, "unknownuser26" <notifications@github.com> wrote:












Hello, I had the same problem.

I created a VM with Android x86 and stored the certificate as trusted via root, then everything worked so well. Unfortunately, it is probably a security feature of Android that self-signed certificates only work in the browser.

**Comment by j-st1** [comment]
Another workaround for Android phones rooted and running Magisk: Temporary installing the Module "Move Certificates" works as well. This will move the certificate to system and the 360 app will not throw the exception anymore.
